### ISSUE TITLE
建议添加 EasyConnect 替换方案

### ISSUE THREAD

**Issue by Toby-Shi-cloud** [buaahub/awesome-buaa#12]
众所周知EasyConnect并不好用，目前已知有以下方案：
- [EasierConnect](https://github.com/lyc8503/EasierConnect): 一个命令行版本，不直接代理网络，只开放sock5端口，可以用clash等设置规则只让需要vpn的流量经过。
- [docker-easyconnect](https://github.com/docker-easyconnect/docker-easyconnect): 将EasyConnect封装在docker中。

**Comment by Dr-Bluemond** [comment]
好的，感谢提案！
